# Generated by Django 2.2.12 on 2020-05-25 05:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20200525_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 5, 53, 57, 824510, tzinfo=utc)),
        ),
    ]
