# Generated by Django 2.2.12 on 2020-05-25 06:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20200525_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 6, 20, 55, 854132, tzinfo=utc)),
        ),
    ]
